schema_version = "1.0.0"

id = "bdk_addon"
version = "2.0.3"
name = "Unreal BDK"
tagline = "Makes Blender a level editor for games running on Unreal 1 and 2"
maintainer = "Colin Basnett <cmbasnett@gmail.com>"
type = "add-on"

website = "https://github.com/DarklightGames/bdk_addon/"

tags = ["Game Engine"]

blender_version_min = "4.5.0"
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "linux-x64"]

# For some bizarre reason, Blender 4.5 shipped with two different versions of Python
# for Linux (3.13) and Windows (3.11).
wheels = [
  "./wheels/bdk_py-0.1.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/bdk_py-0.1.1-cp311-cp311-win_amd64.whl",
  "./wheels/t3dpy-0.1.8-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/t3dpy-0.1.8-cp311-cp311-win_amd64.whl",
  "./wheels/networkx-3.3-py3-none-any.whl",
]

# Optional: build setting.
# https://docs.blender.org/manual/en/dev/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "/.git/",
  "/venv/",
  "/.github/",
  "/.idea/",
  "__pycache__/",
  ".gitignore",
]

[permissions]
files = "Read and write files such as terrain heightmaps"
clipboard = "Copy and paste T3D data"
